# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
codecov: true
coveralls: true
os:
  - linux
  # - osx
julia:
  - 0.7
  - 1.0
  - 1.1

notifications:
    email:
      recipients:
        - donsadit@gmail.com
        - kyriox@gmail.com
        - mgraffg@gmail.com
        - sabinomiranda@gmail.com
        - dmocteo@gmail.com

    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
  global:
    - DISABLE_AMEND_COVERAGE_FROM_SRC=yes

# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
after_success:
  # - julia -e 'cd(Pkg.dir("SimilaritySearch")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'cd(Pkg.dir("SimilaritySearch")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("SimilaritySearch")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
